#!/bin/bash

#  Copyright 2007-2008 Simon Hürlimann <simon.huerlimann@cyt.ch>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.


# Commandline Handling
if [ "$1" == "--force" ] ; then
	FORCE="true"
	shift
fi

if [ "$1" == "--help" ] ; then
	echo "Usage: $(basename $0) [--force] [REPOSITORY_ROOT]"
	exit 2
fi

REPOSITORY_ROOT=${1:-sysadmin:/etc/puppet}

# Options
# =======
PUP_CONF=${PUP_CONF:-/etc/puppet-tools/puppet-tools.conf}

# Defaults
MODULES_REPOSITORY="$REPOSITORY_ROOT/modules"
NODE_REPOSITORY="$REPOSITORY_ROOT/manifests/nodes"

MODULES_PATH=${MODULES_PATH:-/etc/puppet/modules}
NODE_PATH=${NODE_PATH:-/etc/puppet/manifests/nodes}

# Operations
# ==========
function init() {

	mkdir -p "$(dirname $PUP_CONF)"
	if [ "$FORCE" == "true" -o ! -e "$PUP_CONF" ] ; then
		echo "MODULES_REPOSITORY=$MODULES_REPOSITORY" > $PUP_CONF
		echo "MODULES_PATH=$MODULES_PATH" >> $PUP_CONF
		echo "NODE_REPOSITORY=$NODE_REPOSITORY" >> $PUP_CONF
		echo "NODE_PATH=$NODE_PATH" >> $PUP_CONF
	fi

	mkdir -p $MODULES_PATH
	mkdir -p $NODE_PATH
	darcs init --repodir $NODE_PATH
}

# Main
# ====
pushd . >/dev/null
	init
popd >/dev/null
