#!/bin/bash

#  Copyright 2007-2008 ZytoLabor <sysadmin@zyto-labor.com>
#  Copyright 2007-2008 Simon Hürlimann (ZytoLabor) <simon.huerlimann@cyt.ch>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.


# Options
# =======
USER=$1

PUPPET_PATH=${PUPPET_PATH:-/etc/puppet}
USERS_PATH=${NODES_PATH:-$PUPPET_PATH/manifests/users}

# Main
# ====
user_path=$USERS_PATH/$USER.pp

pushd . >/dev/null
cd $PUPPET_PATH
	# Show what's new and record if something changed
	darcs whatsnew $user_path && darcs record $user_path

	# Open editor
	editor $user_path

	# Record changes
	darcs record $user_path
popd >/dev/null
