#!/bin/bash

#  Copyright 2007 Simon Hürlimann <simon.huerlimann@cyt.ch>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.


# Options
# =======
NODE=$1
NODE_IP=$2
CLIENT=${3:-cyt}
INHERITS=${4:-cyt_server}

MODULES_PATH=${MODULES_PATH:-/etc/puppet/modules}
NODE_FQDN=${NODE_FQDN:-$NODE.$(hostname --domain)}
NODE_PATH=${NODE_PATH:-/etc/puppet/manifests/nodes}

node_manifest=$NODE_PATH/$NODE.pp

if [ $# -lt 2 ] ; then
	echo "usage $(basename $0): <NODE> <IP> [<CLIENT> <PARENT CLASS>]"
	exit 2
fi

# Operations
# ==========
function sign_node() {
	# Sign node certificate
	if sudo puppetca --list | grep $NODE_FQDN > /dev/null; then
		echo "Sign certificate"
		sudo puppetca --sign $NODE_FQDN
	else
		echo "No certificate to sign"
	fi
}

function create_node() {
	echo "Create node '$NODE'"

	# Import declaration
	echo "# Imports" > $node_manifest
	echo "# =======" >> $node_manifest
	echo "# System:" >> $node_manifest
	echo 'import "network"' >> $node_manifest
	echo 'import "apt"' >> $node_manifest
	echo >> $node_manifest

	# Domain declaration
	echo "# Client:" >> $node_manifest
	echo "import \"$CLIENT\"" >> $node_manifest
	echo >> $node_manifest

	# Service declaration
	echo "# Services:" >> $node_manifest
	echo 'import "xen"' >> $node_manifest
	echo >> $node_manifest
	
	# Class declaration
	echo "# Node" >> $node_manifest
	echo "# ====" >> $node_manifest
	echo "node $NODE inherits $INHERITS {" >> $node_manifest
	echo "	# System" >> $node_manifest
	echo "	# ======" >> $node_manifest
	echo "	include client_$CLIENT" >> $node_manifest
	echo "	network_interface { \$fqdn: host_ip => '$NODE_IP' }" >> $node_manifest
	echo "	include cyt_nfs_home" >> $node_manifest
	echo "	include xen_guest" >> $node_manifest
	echo "	include apt" >> $node_manifest
	echo >> $node_manifest
	echo "	# Services" >> $node_manifest
	echo "	# ========" >> $node_manifest

	echo "}" >> $node_manifest
}

# Main
# ====
create_node
pushd . >/dev/null
	cd $NODE_PATH
	darcs add $NODE.pp
	darcs rec --all --patch-name "New node '$NODE'" $NODE.pp
	darcs push --all
popd >/dev/null

sudo /etc/init.d/puppetmaster restart

sign_node
