#!/bin/bash

#  Copyright 2007-2008 Simon Hürlimann <simon.huerlimann@cyt.ch>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

set -e

# Options
# =======
MODULES=${1:-$(pup-mod-ls)}

MODULES_PATH=${MODULES_PATH:-/etc/puppet/modules}

# Config File
PUP_CONF=${PUP_CONF:-/etc/puppet-tools/puppet-tools.conf}
source $PUP_CONF

if [ "$1" == "--all" ] ; then
	options="--all"
	shift
fi

# Operations
# ==========
function push_module() {
local module=$1

pushd . >/dev/null
cd $MODULES_PATH/$module

	darcs push $options || err=$?
	if [ "$err" == 2 ] ; then # probably no repository
		read -p "Do you want to put the '$module' to '$MODULES_REPOSITORY' [Yn]?: " answer
		if ! [ "${answer:0:1}" == 'N' -o "${answer:0:1}" == 'n' ] ; then
			pup-mod-put $module $MODULES_REPOSITORY
		fi
	fi

popd >/dev/null
}

function push_all() {
	for module in $MODULES ; do
		module_name=$(basename $module)
		echo "Module '$module_name':"
		push_module $module
        done
}

# Main
# ====
push_all
