#!/bin/bash

#  Copyright 2007-2008 ZytoLabor <sysadmin@zyto-labor.com>
#  Copyright 2007-2008 Simon Hürlimann (ZytoLabor) <simon.huerlimann@cyt.ch>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.


# Options
# =======
DOMAIN=$1
shift
SERVICES=$@

MODULES_PATH=${MODULES_PATH:-/etc/puppet/modules}

manifest=/etc/puppet/modules/$DOMAIN/manifests/init.pp

if [ $# -lt 1 ] ; then
	echo "usage $(basename $0): <DOMAIN> <MODULE:CLASS>..."
	exit 2
fi

# Operations
# ==========
function add_service() {
local service=$1

local service_module=$(echo $service | cut -d : -f 1)
local service_class=$(echo $service | cut -d : -f 2)

local class=${DOMAIN}_${service_class}

	echo "Add service '$service' as class '$class'"
	
	# Import declaration
	echo "import \"$service_module\"" >> $manifest
	echo "class $class inherits $service_class {" >> $manifest
	echo "}" >> $manifest
}

function add_services_to_domain() {
	module_dir=$MODULES_PATH/$DOMAIN
	pushd . >/dev/null
	cd $module_dir
	
		for service in $SERVICES ; do
			add_service $service
		done

		darcs record --all --patch-name "Added services $SERVICES to domain '$DOMAIN'"
	popd >/dev/null
}

# Main
# ====
add_services_to_domain
