#!/bin/bash

#  Copyright 2007 Simon Hürlimann <simon.huerlimann@cyt.ch>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.


# Options
# =======
MODULES_PATH=${MODULES_PATH:-/etc/puppet/modules}
REGEXP="$1"
MODULE=${2:-$(pup-mod-ls)}

if [ $# -lt 1 ] ; then
	echo "Usage: $(basename $0) <REGEXP> [<MODULE>]"
	exit 2
fi

# Main
# ====
grep --recursive $REGEXP $MODULES_PATH | grep -v _darcs
