#!/bin/bash

#  Copyright 2007 Simon Hürlimann <simon.huerlimann@cyt.ch>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

set -e

# Options
# =======
MODULE=$1

MODULES_PATH=${MODULES_PATH:-/etc/puppet/modules}

if [ $# -lt 1 ] ; then
	echo "Usage: $(basename $0) <MODULE>"
	exit 2
fi

# Methods
# =======
function create_module() {
	# module class
	echo "class ${MODULE} {" >> manifests/init.pp
	echo "}" >> manifests/init.pp
}

# Main
# ====
module_dir=$MODULES_PATH/$MODULE

mkdir -p $module_dir

pushd . >/dev/null
cd $module_dir
	if [ ! -d _darcs ] ; then
		darcs init
	fi

	mkdir -p manifests
	mkdir -p templates
	create_module

	# Run create hooks
	$CREATE_HOOK
	
	# Record changes
        darcs record --look-for-adds --all --patch-name "Initial version of module '$MODULE'"
	
	# Push records
	pup-mod-put $MODULE
popd >/dev/null
