#!/bin/bash

#  Copyright 2007-2008 ZytoLabor <sysadmin@zyto-labor.com>
#  Copyright 2007-2008 Simon Hürlimann (ZytoLabor) <simon.huerlimann@cyt.ch>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.


# Options
# =======
CLIENT=$1
DOMAIN=${2:-$CLIENT.ch}

MODULES_PATH=${MODULES_PATH:-/etc/puppet/modules}

manifest=/etc/puppet/modules/$CLIENT/manifests/init.pp

if [ $# -lt 1 ] ; then
	echo "Usage: $(basename $0) <CLIENT> [<DOMAIN>]"
	exit 2
fi

# Operations
# ==========
function create_client() {
	pup-mod-new $CLIENT
	
	module_dir=$MODULES_PATH/$CLIENT
	pushd . >/dev/null
	cd $module_dir
	
		echo "Create client '$CLIENT'"

		# Client declaration
		echo "# Client" >> $manifest
		echo "# ======" >> $manifest
		echo >> $manifest
		echo 'import "client"' >> $manifest
		echo "class client_$CLIENT {" >> $manifest
		echo "	client_srv_dirs { \"$DOMAIN\":" >> $manifest
		echo "		name   => \"$DOMAIN\"," >> $manifest
		echo "		domain => \"$DOMAIN\"" >> $manifest
		echo '	}' >> $manifest
		echo >> $manifest
		echo "	client_accounts { \"$DOMAIN\": name => \"$DOMAIN\" }" >> $manifest
		echo '}' >> $manifest

		for service in $SERVICES ; do
			add_service $service
		done

		darcs record --all --patch-name "Added client_$CLIENT class"
	popd >/dev/null
}

# Main
# ====
create_client
pup-mod-push --all $CLIENT
