#!/bin/bash

#  Copyright 2007-2008 ZytoLabor <sysadmin@zyto-labor.com>
#  Copyright 2007-2008 Simon Hürlimann (ZytoLabor) <simon.huerlimann@cyt.ch>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

set -e

# Options
# =======
MODULES_PATH=${MODULES_PATH:-/etc/puppet/modules}

function list_imports() {
local module=$1

	pushd . >/dev/null
		cd $MODULES_PATH/$module

		TEMP_DIR=$(mktemp -d)

		find manifests/ -name '*.pp' | sed 's#^manifests/\(.*\)\.pp#\1#p' | sort -u >$TEMP_DIR/locals
		find manifests/ -name '*.pp' -exec egrep '[[:space:]]*import' {} \; | sed -n 's/import "\(.*\)"/\1/p' | egrep -v "^$module/" | sort -u >$TEMP_DIR/imports

		comm -2 -3 $TEMP_DIR/imports $TEMP_DIR/locals

		rm -rf $TEMP_DIR
	popd >/dev/null
}

function list_all_imports() {
	for module in $(pup-mod-ls) ; do
	        list_imports $module
        done | sort -u
}

function list_missing_imports() {
	TEMP_DIR=$(mktemp -d)

	pup-mod-dep | sort -u >$TEMP_DIR/imports
	pup-mod-ls | sort -u >$TEMP_DIR/modules
	
	comm -2 -3 $TEMP_DIR/imports $TEMP_DIR/modules

	rm -rf $TEMP_DIR
}

# Main
# ====
action=list_all_imports

[ "$1" == "missing" ] && action=list_missing_imports
[ "$1" == "show" ] && action=list_imports

$action
